name: OpenMusicPlayer
options:
  xcodeVersion: "11.3"
  minimumXcodeGenVersion: "2.11.0"
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "13.0"
  bundleIdPrefix: com.molayab.musicplayer-ui
settings:
  base:
    SDKROOT: "iphoneos"
    VERSIONING_SYSTEM: "apple-generic"
    SWIFT_VERSION: "5.0"
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
  configs:
    Debug:
      DEBUG: "1"
      ONLY_ACTIVE_ARCH: YES
      ENABLE_TESTABILITY: YES
      GCC_SYMBOLS_PRIVATE_EXTERN: NO
      ASSETCATALOG_COMPILER_OPTIMIZATION: "time"
      OTHER_SWIFT_FLAGS:
          -Onone
          -enable-batch-mode
    Release:
      DEBUG: "0"
      SWIFT_OPTIMIZATION_LEVEL: "-Osize"
      SWIFT_COMPILATION_MODE: "wholemodule"
      ASSETCATALOG_COMPILER_OPTIMIZATION: "space"
      BUILD_LIBRARY_FOR_DISTRIBUTION: YES
targets:
  App:
    platform: iOS
    type: application
    sources: [App]
    dependencies:
      - target: Core
      - target: UI
      - sdk: Foundation.framework
      - sdk: Combine.framework
  AppTests:
    type: bundle.unit-test
    platform: iOS
    sources: [Tests/AppTests]
    dependencies:
      - target: App
  UI:
    type: framework
    platform: iOS
    sources: [UI]
  Core:
    type: framework
    platform: iOS
    sources: [Core]
  CoreTests:
    type: bundle.unit-test
    platform: iOS
    sources: [Tests/CoreTests]
    dependencies:
      - target: Core
