name: OpenMusicPlayer
options:
  xcodeVersion: "12.0"
  minimumXcodeGenVersion: "2.11.0"
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "14.0"
  bundleIdPrefix: com.molayab.musicplayer
settings:
  base:
    SDKROOT: "iphoneos"
    VERSIONING_SYSTEM: "apple-generic"
    SWIFT_VERSION: "5.2"
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
  configs:
    Debug:
      DEBUG: "1"
      ONLY_ACTIVE_ARCH: YES
      ENABLE_TESTABILITY: YES
      GCC_SYMBOLS_PRIVATE_EXTERN: NO
      ASSETCATALOG_COMPILER_OPTIMIZATION: "time"
      OTHER_SWIFT_FLAGS:
          -Onone
          -enable-batch-mode
    Release:
      DEBUG: "0"
      SWIFT_OPTIMIZATION_LEVEL: "-Osize"
      SWIFT_COMPILATION_MODE: "wholemodule"
      ASSETCATALOG_COMPILER_OPTIMIZATION: "space"
      BUILD_LIBRARY_FOR_DISTRIBUTION: YES
targets:
  App:
    info:
        path: App/Info.plist
        properties:
            UIApplicationSceneManifest:
                UIApplicationSupportsMultipleScenes: true
            UIApplicationSupportsIndirectInputEvents: true
            UILaunchScreen: ""
            UIRequiredDeviceCapabilities: [armv7]
            UISupportedInterfaceOrientations:
                - UIInterfaceOrientationPortrait
                - UIInterfaceOrientationLandscapeLeft
                - UIInterfaceOrientationLandscapeRight
            UISupportedInterfaceOrientations:
                - UIInterfaceOrientationPortrait
                - UIInterfaceOrientationPortraitUpsideDown
                - UIInterfaceOrientationLandscapeLeft
                - UIInterfaceOrientationLandscapeRight
            NSAppleMusicUsageDescription: "This app requires access to play music"
    platform: iOS
    type: application
    sources: [App]
    dependencies:
      - target: Core
      - target: UI
      - sdk: Foundation.framework
      - sdk: Combine.framework
  AppTests:
    type: bundle.unit-test
    platform: iOS
    sources: [Tests/AppTests]
    dependencies:
      - target: App
  UI:
    info:
        path: UI/Info.plist
    type: framework
    platform: iOS
    sources: 
      - UI
      - UI/Resources/Assets.xcassets
      - UI/Resources/Colors.xcassets
  Core:
    info:
        path: Core/Info.plist
    type: framework
    platform: iOS
    sources: [Core]
  CoreTests:
    type: bundle.unit-test
    platform: iOS
    sources: [Tests/CoreTests]
    dependencies:
      - target: Core
